[WIP] first-page poc
marmelab/quarto-symfony pull request #1
Opened 2018-06-18 13:42 UTC by JulienMattiussi

https://trello.com/c/sSmiLBOh

2018-06-19 07:09 UTC, alexisjanvier requested changes
There is too much files for review ... Maybe did you add the `vendor` folder content before adding it to the `.gitignore`?

2018-06-19 08:43 UTC, Kmaschta commented
Can you please not commit the vendor folder .. ?

2018-06-19 19:31 UTC, alexisjanvier requested changes
Could you add a screenshot?

2018-06-19 19:31 UTC, alexisjanvier commented on Makefile
> +	docker build -t php docker/php
It's easier to use your existing services.

2018-06-19 19:31 UTC, alexisjanvier commented on docker/php/Dockerfile
> +RUN apt-get install -y libpq-dev \
This installation could be done at the same time as the first `RUN`

2018-06-19 19:31 UTC, alexisjanvier commented on quarto/config/packages/doctrine.yaml
> +        dbname: 'quarto'
This information should come from environment variables

2018-06-19 19:31 UTC, alexisjanvier commented on quarto/src/Controller/MainController.php
> +use Symfony\Component\HttpFoundation\Response;
Did you install a Php linter? for example to follow the [PSR-2](https://www.php-fig.org/psr/psr-2/) standard. Someting like [PHP Coding Standards Fixer](http://cs.sensiolabs.org/) or [PHP Formatter](https://marketplace.visualstudio.com/items?itemName=Sophisticode.php-formatter).

Here for example it seems to me that an empty line is missing.

2018-06-20 07:40 UTC, alexisjanvier approved these changes

2018-06-20 07:41 UTC, merged